/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DynamicERP.frames.purchase;

import DB.PAK_DB;
import DB.PAK_GENERAL_DB;
import DynamicERP.dialoge.viewforms.dialogeClass;
import java.awt.Graphics;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import DynamicERP.frames.newdataentry.FIRMREC;
import DynamicERP.frames.relationalforms.CUSTREC;
import DynamicERP.frames.relationalforms.RECOVERY;
import static DynamicERP.frames.purchase.PURCHASE.buildAllComboBoxModel;
import DynamicERP.frames.sales.SALES;
import com.toedter.calendar.JDateChooser;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;
import javax.swing.KeyStroke;
import logical.EcLogger;

/**
 *
 * @author Shan
 */
public class PakPurchaseFieldPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form PakPurchaseFieldPanel
     */
    public PakPurchaseFieldPanel1() {
        initComponents();
        styleComboBox(pName);
        textFieldsEditableProducts(true); 
//        KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
//        Set<KeyStroke> keys = new HashSet<>();
//        keys.add(enter);
//        KeyboardFocusManager.getCurrentKeyboardFocusManager().setDefaultFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, keys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seek = new javax.swing.JTextField();
        seqNo = new javax.swing.JTextField();
        pName = new javax.swing.JComboBox();
        totalQty = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        taxRs = new javax.swing.JTextField();
        taxPer = new javax.swing.JTextField();
        grossAmt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        discRs = new javax.swing.JTextField();
        discPer = new javax.swing.JTextField();
        netAmt = new javax.swing.JTextField();
        free = new javax.swing.JTextField();
        damage = new javax.swing.JTextField();
        tdo = new javax.swing.JTextField();
        fmr = new javax.swing.JTextField();
        fmrrs = new javax.swing.JTextField();
        ctn = new javax.swing.JTextField();
        pcs = new javax.swing.JTextField();
        custom = new javax.swing.JTextField();
        expDate = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1293, 20));

        seek.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        seek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seekKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seekKeyReleased(evt);
            }
        });

        seqNo.setEditable(false);
        seqNo.setBackground(new java.awt.Color(255, 255, 204));
        seqNo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        seqNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seqNoActionPerformed(evt);
            }
        });

        pName.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        pName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Chocorama Van Rs 5 1 x 12 Box", "Item 3", "Item 4" }));
        pName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                pNamePopupMenuWillBecomeVisible(evt);
            }
        });
        pName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameActionPerformed(evt);
            }
        });

        totalQty.setBackground(new java.awt.Color(255, 255, 204));
        totalQty.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        totalQty.setText("0");
        totalQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalQtyActionPerformed(evt);
            }
        });
        totalQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalQtyKeyReleased(evt);
            }
        });

        rate.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rate.setText("0");
        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });
        rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rateKeyReleased(evt);
            }
        });

        taxRs.setBackground(new java.awt.Color(255, 204, 204));
        taxRs.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        taxRs.setText("0");
        taxRs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taxRsKeyReleased(evt);
            }
        });

        taxPer.setBackground(new java.awt.Color(255, 204, 204));
        taxPer.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        taxPer.setText("0");
        taxPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxPerActionPerformed(evt);
            }
        });
        taxPer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taxPerKeyReleased(evt);
            }
        });

        grossAmt.setBackground(new java.awt.Color(153, 255, 204));
        grossAmt.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        grossAmt.setText("0");
        grossAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grossAmtKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oracledms/frames/resources/db_rem1.png"))); // NOI18N

        discRs.setBackground(new java.awt.Color(153, 255, 153));
        discRs.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        discRs.setText("0");
        discRs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discRsKeyReleased(evt);
            }
        });

        discPer.setBackground(new java.awt.Color(153, 255, 153));
        discPer.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        discPer.setText("0");
        discPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discPerActionPerformed(evt);
            }
        });
        discPer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discPerKeyReleased(evt);
            }
        });

        netAmt.setEditable(false);
        netAmt.setBackground(new java.awt.Color(255, 255, 204));
        netAmt.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        netAmt.setText("0.0");

        free.setBackground(new java.awt.Color(255, 255, 204));
        free.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        free.setText("0");
        free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeActionPerformed(evt);
            }
        });
        free.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                freeKeyReleased(evt);
            }
        });

        damage.setBackground(new java.awt.Color(255, 255, 204));
        damage.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        damage.setText("0");
        damage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damageActionPerformed(evt);
            }
        });
        damage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                damageKeyReleased(evt);
            }
        });

        tdo.setBackground(new java.awt.Color(153, 255, 153));
        tdo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tdo.setText("0");
        tdo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tdoKeyReleased(evt);
            }
        });

        fmr.setBackground(new java.awt.Color(153, 255, 153));
        fmr.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fmr.setText("0");
        fmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmrActionPerformed(evt);
            }
        });
        fmr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fmrKeyReleased(evt);
            }
        });

        fmrrs.setBackground(new java.awt.Color(153, 255, 153));
        fmrrs.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        fmrrs.setText("0");
        fmrrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmrrsActionPerformed(evt);
            }
        });
        fmrrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fmrrsKeyReleased(evt);
            }
        });

        ctn.setBackground(new java.awt.Color(255, 255, 204));
        ctn.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        ctn.setText("0");
        ctn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctnActionPerformed(evt);
            }
        });
        ctn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ctnKeyReleased(evt);
            }
        });

        pcs.setBackground(new java.awt.Color(255, 255, 204));
        pcs.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        pcs.setText("0");
        pcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcsActionPerformed(evt);
            }
        });
        pcs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pcsKeyReleased(evt);
            }
        });

        custom.setEditable(false);
        custom.setBackground(new java.awt.Color(255, 255, 204));
        custom.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seqNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(seek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ctn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pcs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(totalQty, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grossAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(discPer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(discRs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(taxPer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(taxRs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(free, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tdo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fmr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fmrrs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(netAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(custom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fmrrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(netAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custom))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(free, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taxPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(taxRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(seek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seqNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(grossAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ctn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getDamage() {
        return damage;
    }

    public void setDamage(JTextField damage) {
        this.damage = damage;
    }

    public JTextField getFree() {
        return free;
    }

    public void setFree(JTextField free) {
        this.free = free;
    }

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateActionPerformed

    private void taxPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxPerActionPerformed

    private void discPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discPerActionPerformed

    private void seekKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seekKeyReleased
        if((evt.getKeyCode() == KeyEvent.VK_ENTER) && seek.getText().isEmpty()) {
            try 
            {
                dialogeClass.createViewProductRecWin();
            } catch (SQLException ex) {
                Logger.getLogger(SALES.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(DynamicERP.dialoge.viewforms.ViewForm11.isSaved){
                seek.setText(dialogeClass.codeProductRec);
                
                seek.requestFocus();seek.selectAll();
            }
        }else if((evt.getKeyCode() == KeyEvent.VK_ENTER)&&!seek.getText().isEmpty()) {
            ctn.requestFocus();ctn.selectAll();
        }
        
                try {
                    updateComboBox(seek, pName);
                } catch (Exception ex) {
                    Logger.getLogger(RECOVERY.class.getName()).log(Level.SEVERE, null, ex);
                }
                setAllFieldData();
    }//GEN-LAST:event_seekKeyReleased

    private void pNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameActionPerformed
        System.out.println("seek.getText():"+seek.getText()+" :<=|--|=>: getCode(getSubName()):"+getCode(getSubName()));
//        /*
        if(seek.getText().equals(getCode(getSubName()))){
//            System.out.println("M");
        }else{
            seek.setText(getCode(getSubName()));
            rate.setText(getRate(getSubName()));
//            System.out.println("Not M");
        }//
        setAllFieldData();
//        */

    }//GEN-LAST:event_pNameActionPerformed

    private void pNamePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pNamePopupMenuWillBecomeVisible
        PAK_DB data =new PAK_DB();
        Connection conn;
        try {
            conn = data.connect_database();        
            pName.setModel(buildAllComboBoxModel());
//            if(setSelectedComboItem(seek,pName,((!seek.getText().isEmpty())?data.find_supp_name_by_code(conn, seek.getText()):""))){
            if(setSelectedComboItem(seek,pName,((!seek.getText().isEmpty())?data.find_product_name_by_code(conn, seek.getText()):""))){
                
            }else{
                seek.setText(getCode(getSubName()));
                rate.setText(getRate(getSubName()));
                
                //===================================
                frmGrossAmount();
                frmNetAmount();
            }
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(CUSTREC.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CUSTREC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pNamePopupMenuWillBecomeVisible

    private void seqNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seqNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seqNoActionPerformed

    private void taxPerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxPerKeyReleased
        frmTaxRs();
        frmNetAmount();
    }//GEN-LAST:event_taxPerKeyReleased

    private void taxRsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxRsKeyReleased
        frmTaxPer();
        frmNetAmount();
    }//GEN-LAST:event_taxRsKeyReleased

    private void discRsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discRsKeyReleased
        frmDiscPer();
        frmNetAmount();
    }//GEN-LAST:event_discRsKeyReleased

    private void discPerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discPerKeyReleased
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_discPerKeyReleased

    private void rateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateKeyReleased
        try{
            BigDecimal temp1 = (BigDecimal.valueOf(Float.parseFloat(totalQty.getText()))).multiply(BigDecimal.valueOf(Float.parseFloat(rate.getText())));grossAmt.setText(round((temp1),3)+"");
        }catch(NumberFormatException ex){
        }
        frmTaxRs();
        frmFmrRs();
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_rateKeyReleased

    private void grossAmtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grossAmtKeyReleased
       /* try{
                             switch (pType.getSelectedItem()+"") 
        {
           case "SFT":
              rate.setText(round((Float.parseFloat(grossAmt.getText())/Float.parseFloat(totalSize.getText())),3)+"");
               
               break;
           case "RFT":
              rate.setText(round((Float.parseFloat(grossAmt.getText())/Float.parseFloat(totalSize.getText())),3)+"");
              break;
           case "PER PIECE":*/
            if(Float.parseFloat(totalQty.getText())!=0){
                rate.setText(round((Float.parseFloat(grossAmt.getText())/Float.parseFloat(totalQty.getText())),3)+"");
            }
/*              break;
           case "CUSTOME":
              rate.setText(round((Float.parseFloat(grossAmt.getText())/Float.parseFloat(totalSize.getText())),3)+"");
              break;
        }
     
         
        }catch(NumberFormatException ex){
            System.out.println("eXCEPTION :"+ex);
//            if(ex.getMessage().matches("empty String")){
////                System.out.println("Do Nothing: "+ex);
//            }else{
//                JFrame j=new JFrame();
//                j.setAlwaysOnTop(true);
//                JOptionPane.showMessageDialog(j, "Invalid Input", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
////                System.out.println("Number Format is InCorrect: "+ex.getMessage());
//            }
        }
        */
        frmTaxRs();
        frmFmrRs();
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_grossAmtKeyReleased

    private void totalQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalQtyKeyReleased
        try{
            BigDecimal temp1 = (BigDecimal.valueOf(Float.parseFloat(totalQty.getText()))).multiply(BigDecimal.valueOf(Float.parseFloat(rate.getText())));grossAmt.setText(round((temp1),3)+"");
        }catch(NumberFormatException ex){
        }
        frmCtn(getNoOfPcsInCtn());
        frmPcs(getNoOfPcsInCtn());
        
        frmTaxRs();
        frmFmrRs();
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_totalQtyKeyReleased

    private void totalQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalQtyActionPerformed

    private void freeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freeActionPerformed

    private void freeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_freeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_freeKeyReleased

    private void damageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damageActionPerformed

    private void damageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_damageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_damageKeyReleased

    private void seekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seekKeyPressed
     /*   if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
    //            dialogeClass.createViewSalesWin();
                dialogeClass.createViewProductRecWin();
            } catch (SQLException ex) {
                Logger.getLogger(PakPurchaseFieldPanel1.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(DynamicERP.dialoge.viewforms.ViewForm11.isSaved){
                seek.setText(dialogeClass.codeProductRec);
            }else{
            }
        }
        try {
            updateComboBox(seek, pName);
        } catch (Exception ex) {
            Logger.getLogger(PakPurchaseFieldPanel1.class.getName()).log(Level.SEVERE, null, ex);
        }
        setAllFieldData();
       */ 
    }//GEN-LAST:event_seekKeyPressed

    private void tdoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdoKeyReleased
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_tdoKeyReleased

    private void fmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmrActionPerformed

    private void fmrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmrKeyReleased
        frmFmrRs();
        frmNetAmount();
    }//GEN-LAST:event_fmrKeyReleased

    private void fmrrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmrrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmrrsActionPerformed

    private void fmrrsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmrrsKeyReleased
        frmFmrPer();
        frmNetAmount();
    }//GEN-LAST:event_fmrrsKeyReleased

    private void ctnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctnActionPerformed

    private void ctnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctnKeyReleased
        frmQty();
        try{
           BigDecimal temp1 = (BigDecimal.valueOf(Float.parseFloat(totalQty.getText()))).multiply(BigDecimal.valueOf(Float.parseFloat(rate.getText())));grossAmt.setText(round((temp1),3)+"");
        }catch(NumberFormatException ex){
        }
        frmTaxRs();
        frmFmrRs();
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_ctnKeyReleased

    private void pcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcsActionPerformed

    private void pcsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcsKeyReleased
        frmQty();
        try{
            BigDecimal temp1 = (BigDecimal.valueOf(Float.parseFloat(totalQty.getText()))).multiply(BigDecimal.valueOf(Float.parseFloat(rate.getText())));grossAmt.setText(round((temp1),3)+"");
        }catch(NumberFormatException ex){
        }
        frmTaxRs();
        frmFmrRs();
        frmDiscRs();
        frmNetAmount();
    }//GEN-LAST:event_pcsKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ctn;
    private javax.swing.JTextField custom;
    private javax.swing.JTextField damage;
    private javax.swing.JTextField discPer;
    private javax.swing.JTextField discRs;
    private com.toedter.calendar.JDateChooser expDate;
    private javax.swing.JTextField fmr;
    private javax.swing.JTextField fmrrs;
    private javax.swing.JTextField free;
    private javax.swing.JTextField grossAmt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField netAmt;
    private javax.swing.JComboBox pName;
    private javax.swing.JTextField pcs;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField seek;
    private javax.swing.JTextField seqNo;
    private javax.swing.JTextField taxPer;
    private javax.swing.JTextField taxRs;
    private javax.swing.JTextField tdo;
    private javax.swing.JTextField totalQty;
    // End of variables declaration//GEN-END:variables

    public JTextField getCustom() {
        return custom;
    }

    public void setCustom(JTextField custom) {
        this.custom = custom;
    }

    public JDateChooser getExpDate() {
        return expDate;
    }

    public void setExpDate(JDateChooser expDate) {
        this.expDate = expDate;
    }

    public JTextField getPcs() {
        return pcs;
    }

    public JTextField getCtn() {
        return ctn;
    }

    public JTextField getFmrrs() {
        return fmrrs;
    }

    public void setFmrrs(JTextField fmrrs) {
        this.fmrrs = fmrrs;
    }

    public JTextField getFmr() {
        return fmr;
    }

    public JTextField getTdo() {
        return tdo;
    }

    public JTextField getSeqNo() {
        return seqNo;
    }

    public void setSeqNo(JTextField seqNo) {
        this.seqNo = seqNo;
    }
   
    public void setDiscPer(String discPer) {
        this.discPer.setText(discPer);
    }

    public void setDiscRs(String discRs) {
        this.discRs.setText(discRs);
    }

    public void setGrossAmt(String grossAmt) {
        this.grossAmt.setText(grossAmt);
    }

    public void setNetAmt(String netAmt) {
        this.netAmt.setText(netAmt);
    }

    public void setpName(String pName) {
        try {
                this.pName.setModel(buildOneComboBoxModel(pName));
            } catch (Exception ex) {
                Logger.getLogger(PakPurchaseFieldPanel1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    public void setRate(String rate) {
        this.rate.setText(rate);
    }

    public void setSeek(String seek) {
        this.seek.setText(seek);
    }

    public void setTaxPer(String taxPer) {
        this.taxPer.setText(taxPer);
    }

    public void setTaxRs(String taxRs) {
        this.taxRs.setText(taxRs);
    }

    public void setTotalQty(String totalQty) {
        this.totalQty.setText(totalQty);
    }

    public JTextField getDiscPer() {
        return discPer;
    }
    public String getDiscPerText() {
        return discPer.getText();
    }

    public JTextField getDiscRs() {
        return discRs;
    }
    public String getDiscRsText() {
        return discRs.getText();
    }

    public JTextField getGrossAmt() {
        return grossAmt;
    }
    public String getGrossAmtText() {
        return grossAmt.getText();
    }

    public JTextField getNetAmt() {
        return netAmt;
    }
    public String getNetAmtText() {
        return netAmt.getText();
    }

    public JComboBox getpName() {
        return pName;
    }

    public JTextField getRate() {
        return rate;
    }
    public String getRateText() {
        return rate.getText();
    }

    public JTextField getSeek() {
        return seek;
    }
    public String getSeekText() {
        return seek.getText();
    }

    public JTextField getTaxPer() {
        return taxPer;
    }
    public String getTaxPerText() {
        return taxPer.getText();
    }

    public JTextField getTaxRs() {
        return taxRs;
    }
    public String getTaxRsText() {
        return taxRs.getText();
    }

    public JTextField getTotalQty() {
        return totalQty;
    }
    public String getTotalQtyText() {
        return totalQty.getText();
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setSeqNoTextField(JTextField seqNoTextField) {
        this.seqNo = seqNoTextField;
    }

    public JTextField getSeqNoTextField() {
        return seqNo;
    }
    public void setSeqNoText(String seqNoTextField) {
        this.seqNo.setText(seqNoTextField);
    }

    public String getSeqNoText() {
        return seqNo.getText();
    }
    public boolean setSelectedComboItem(JTextField textField,JComboBox comboBox, String value)
    {
        boolean tf=false;
        String item;
        if(value!=null){
            for (int i = 0; i < comboBox.getItemCount(); i++)
            {
                item = getSubName((String)comboBox.getItemAt(i));
                System.out.println("item:"+item);
                if (!item.isEmpty())
                {
                    if (item.equals(value))
                    {
                        comboBox.setSelectedIndex(i);
                        tf=true;
                        break;
                    }
                }else{
                    System.out.println(">== Message: Item is empty. . . ");
                    JFrame j=new JFrame();
                    j.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(j, "First Add Items in : "+comboBox.getName(), "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                }
            }   
        }else{
            System.out.println(">== Message: Value could not be  Selected . . . ");
            comboBox.setSelectedIndex(0);
        }
        return tf;
    }
    private void updateComboBox(JTextField textField,JComboBox comboBox) throws Exception {
        comboBox.setModel(buildOneComboBoxModel(textField.getText()));
    }
    public static DefaultComboBoxModel buildAllComboBoxModel() throws Exception {
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        PAK_DB data =new PAK_DB();
        Connection conn;
        ArrayList<String> elements = new <String> ArrayList() ;
        try {
            conn = data.connect_database();
            boolean tf=false;
            elements=data.find_all_product_name_size_by_code(conn);
            if(elements!=null){    
                for(String s : elements){
                    comboBoxModel.addElement(s);
                }
            }else{
                JFrame j=new JFrame();
                    j.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(j, "Not Edited", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
            }
            System.out.println("Is Inserted :"+ tf);
            data.close_database(conn);
        } catch (SQLException ex) {
            Logger.getLogger(FIRMREC.class.getName()).log(Level.SEVERE, null, ex);
        }
        return comboBoxModel;
    }
    public DefaultComboBoxModel buildOneComboBoxModel(String id) throws Exception {
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        PAK_DB data =new PAK_DB();
        Connection conn;
        String element="";
        try {
            conn = data.connect_database();
            ArrayList<String> temp;
            if(!id.equals("")){
                temp=data.find_product_rec_by_code(conn, id);
                String s1=null,s2 =null;
                if(temp!=null){
                    for(int i=0;i<temp.size();i++){
                        if(i==1||i==2){//||i==6||i==10){
                            if(i==2){
                                s1 = temp.get(i);
                            }else if(i==1){
                                s2 = temp.get(i);
                            }
                            System.out.println("i="+i+" : "+temp.get(i));
                        }else{
                        }
                        if(i==4){
                            rate.setText(temp.get(i));
                        }
                    }
                    element=s2+" | "+s1;
                    comboBoxModel.addElement(element);
                }else{
                    rate.setText("0.00");
                }
            }else{
                 rate.setText("0.00");
//                JFrame j=new JFrame();
//                j.setAlwaysOnTop(true);
//                J}OptionPane.showMessageDialog(j, "no Id Found");
            }
            data.close_database(conn);
        } catch (SQLException ex) {
            Logger.getLogger(FIRMREC.class.getName()).log(Level.SEVERE, null, ex);
        }
        return comboBoxModel;
    }

    private String getCode(String name) {
        String s="";
        PAK_DB data =new PAK_DB();
        Connection conn;
        try {
            conn = data.connect_database();
            if(!name.equals("")){
                s=data.find_product_code_by_name(conn,name);
//                s=data.find_product_code_by_name(conn,name);
            }else{
//                JFrame j=new JFrame();
//                j.setAlwaysOnTop(true);
//                JOptionPane.showMessageDialog(j, "Emter Id Found");
            }       
            data.close_database(conn);
        } catch (SQLException ex) {
            Logger.getLogger(FIRMREC.class.getName()).log(Level.SEVERE, null, ex);
        }
        return s;
    }

     private String getSubName() {
        String s=pName.getSelectedItem().toString().substring(0, pName.getSelectedItem().toString().indexOf("|")-1);        
        return s;
    }
    private String getSubName(String p) {
        String s=p.substring(0, p.indexOf("|")-1);  
        return s;
    }

    private String getRate(String name) {
        String s="";
        PAK_DB data =new PAK_DB();
        Connection conn;
        try {
            conn = data.connect_database();
            if(!name.equals("")){
                s=data.find_product_rate_by_name(conn,name);
            }else{
//                JFrame j=new JFrame();
//                j.setAlwaysOnTop(true);
//                JOptionPane.showMessageDialog(j, "Emter Id Found");
            }       
            data.close_database(conn);
        } catch (SQLException ex) {
            Logger.getLogger(FIRMREC.class.getName()).log(Level.SEVERE, null, ex);
        }
        return s;
    }
    private String getWeight(String name) {
        String s="";
        PAK_DB data =new PAK_DB();
        Connection conn;
        try {
            conn = data.connect_database();
            if(!name.equals("")){
                s=data.find_product_weight_by_name(conn,name.trim());
            }else{
//                JFrame j=new JFrame();
//                j.setAlwaysOnTop(true);
//                JOptionPane.showMessageDialog(j, "Emter Id Found");
            }       
            data.close_database(conn);
        } catch (SQLException ex) {
            Logger.getLogger(FIRMREC.class.getName()).log(Level.SEVERE, null, ex);
        }
        return s;
    }
    private void styleComboBox(JComboBox combo) {
        combo.setRenderer(new DefaultListCellRenderer() {
            public void paint(Graphics g) {
                super.paint(g);
            }
        });
    }
    public void textFieldsEditableProducts(boolean b) {
         seqNo.setEditable(false);
        seek.setEditable(b);
        ctn.setEditable(b);
        pcs.setEditable(b);
        totalQty.setEditable(b);
        damage.setEditable(b);
        free.setEditable(b);
        pName.setEnabled(b);
        rate.setEditable(b);
        grossAmt.setEditable(b);
        discPer.setEditable(b);
        fmr.setEditable(b);
        fmrrs.setEditable(b);
        tdo.setEditable(b);
        discRs.setEditable(b);
        taxPer.setEditable(b);
        taxRs.setEditable(b);
        netAmt.setEditable(false);
        custom.setEditable(b);
        jLabel2.setEnabled(b);
        expDate.setEnabled(b);
        
    }

    
    public void frmNetAmount() {
        try{
            BigDecimal result1 = ((BigDecimal.valueOf(Float.parseFloat(grossAmt.getText()))).add(BigDecimal.valueOf(Float.parseFloat(taxRs.getText())))).subtract(BigDecimal.valueOf(Float.parseFloat(discRs.getText())));
            result1 = result1.subtract( BigDecimal.valueOf(Float.parseFloat(fmrrs.getText())));
            result1 = result1.subtract( BigDecimal.valueOf(Float.parseFloat(tdo.getText())));
            netAmt.setText(round((result1),3)+"");
        }catch(NumberFormatException ex){
            if(ex.getMessage().matches("empty String")){
//                System.out.println("Do Nothing: "+ex);
            }else{
                JFrame j=new JFrame();
                j.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(j, "Invalid Input", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
                
//                System.out.println("Number Format is InCorrect: "+ex.getMessage());
            }
        }
    }

    private void frmGrossAmount() {
     /*switch (pType.getSelectedItem()+"") 
        {
           case "SFT":
               try{
                    BigDecimal totalQtyBD = BigDecimal.valueOf(Float.parseFloat(totalSize.getText()));
                    BigDecimal rateBD = BigDecimal.valueOf(Float.parseFloat(rate.getText()));
                    BigDecimal temp1 = totalQtyBD.multiply(rateBD);grossAmt.setText(round((temp1),3)+"");
                }catch(NumberFormatException ex){
                }
               break;
           case "RFT":
                try{
                    BigDecimal totalQtyBD = BigDecimal.valueOf(Float.parseFloat(totalSize.getText()));
                    BigDecimal rateBD = BigDecimal.valueOf(Float.parseFloat(rate.getText()));
                    BigDecimal temp1 = totalQtyBD.multiply(rateBD);grossAmt.setText(round((temp1),3)+"");
                }catch(NumberFormatException ex){
                }
               break;
           case "PER PIECE":
                */
                try{
                    BigDecimal totalQtyBD = BigDecimal.valueOf(Float.parseFloat(totalQty.getText()));
                    BigDecimal rateBD = BigDecimal.valueOf(Float.parseFloat(rate.getText()));
                    BigDecimal temp1 = totalQtyBD.multiply(rateBD);grossAmt.setText(round((temp1),3)+"");
                }catch(NumberFormatException ex){
                }
               /*break;
           case "CUSTOME":
               try{
                    BigDecimal totalQtyBD = BigDecimal.valueOf(Float.parseFloat(totalSize.getText()));
                    BigDecimal rateBD = BigDecimal.valueOf(Float.parseFloat(rate.getText()));
                    BigDecimal temp1 = totalQtyBD.multiply(rateBD);grossAmt.setText(round((temp1),3)+"");
                }catch(NumberFormatException ex){
                }
               break;
        }*/
    }

    public void frmDiscRs() {
        String lineL[] = new String[2];
        try {
            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(new File("out.txt"))));
            String line = null;int i=0;
            while ((line = br.readLine()) != null) {lineL[i] = line;i++;}br.close();
        } catch (IOException ex) {
            Logger.getLogger(PURCHASE.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(has_access(new EcLogger().classDeLoade(lineL[0]))){
            try{
                discRs.setText(round(((Float.parseFloat(grossAmt.getText())*Float.parseFloat(discPer.getText()))/100),3)+"");
            }catch(NumberFormatException ex){
                if(ex.getMessage().matches("empty String")){
                //                System.out.println("Do Nothing: "+ex);
                    discRs.setText("0.00");
                }else{
                    JFrame j=new JFrame();
                    j.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(j, "Invalid Input", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
                //                System.out.println("Number Format is InCorrect: "+ex.getMessage());
                }
            }
        }else{
            try{
                float f=Float.parseFloat(grossAmt.getText())-Float.parseFloat(tdo.getText());
                discRs.setText(round(((f*Float.parseFloat(discPer.getText()))/100),3)+"");
            }catch(NumberFormatException ex){
                if(ex.getMessage().matches("empty String")){
                //                System.out.println("Do Nothing: "+ex);
                    discRs.setText("0.00");
                }else{
                    JFrame j=new JFrame();
                    j.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(j, "Invalid Input", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
                //                System.out.println("Number Format is InCorrect: "+ex.getMessage());
                }
            }
        }
    }

    private void frmDiscPer() {
        String lineL[] = new String[2];
        try {
            File fin = new File("out.txt");
            FileInputStream fis = new FileInputStream(fin);
            BufferedReader br = new BufferedReader(new InputStreamReader(fis));
            String line = null;int i=0;
            while ((line = br.readLine()) != null) {lineL[i] = line;i++;}br.close();
        } catch (IOException ex) {
            Logger.getLogger(SALES.class.getName()).log(Level.SEVERE, null, ex);
        }
        EcLogger ec = new EcLogger();
        System.out.println("ec.classDeLoade(lineL[0]) |--<<-->>"+ec.classDeLoade(lineL[0]));
        if(has_access(ec.classDeLoade(lineL[0]))){
            try{
                discPer.setText(round(((Float.parseFloat(discRs.getText())*100)/Float.parseFloat(grossAmt.getText())),3)+"");
             }catch(NumberFormatException ex){

             }
        }else{
                float f=Float.parseFloat(grossAmt.getText())-Float.parseFloat(tdo.getText());
            try{
                discPer.setText(round(((Float.parseFloat(discRs.getText())*100)/f),3)+"");
             }catch(NumberFormatException ex){

             }
        }
        

    }

    public void frmTaxRs() {
        try{
           taxRs.setText(round(((Float.parseFloat(grossAmt.getText()) * Float.parseFloat(taxPer.getText())) / 100),3)+"");
        }catch(NumberFormatException ex){
            if(ex.getMessage().matches("empty String")){
//                System.out.println("Do Nothing: "+ex);
                taxRs.setText("0.00");
            }else{
                JFrame j=new JFrame();
                j.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(j, "Invalid Input", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
                
//                System.out.println("Number Format is InCorrect: "+ex.getMessage());
            }
        }
    }

    private void frmTaxPer() {
        try{
           taxPer.setText(round((Float.parseFloat(taxRs.getText())*100)/Float.parseFloat(grossAmt.getText()),3)+"");
        }catch(NumberFormatException ex){
        }
    }
    private boolean has_access(String string) {
        boolean s1=false;
        PAK_GENERAL_DB data =new PAK_GENERAL_DB();
        Connection conn;
        try {
            conn = data.connect_database();
            String next = data.get_role_from_userLogin(conn,string);
            if(next!=null){
                System.out.println("next"+next);
                String grant = data.get_access_from_grant(conn,"201",next);
                System.out.println("grant"+grant);
                if((1==(grant.compareTo("y")))||(1==(grant.compareTo("Y")))){
                    s1=true;
                }else{
                    s1=false;
                }
            }else{
                JFrame j=new JFrame();
                j.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(j, "Next not found", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
            }
            data.close_database(conn);
        } catch (SQLException ex) {
            Logger.getLogger(SALES.class.getName()).log(Level.SEVERE, null, ex);
        }
        return s1;
    }
    
    public void frmFmrRs() {
        try{
           fmrrs.setText(round(((Float.parseFloat(grossAmt.getText()) * Float.parseFloat(fmr.getText())) / 100),3)+"");
        }catch(NumberFormatException ex){
            if(ex.getMessage().matches("empty String")){
//                System.out.println("Do Nothing: "+ex);
                fmrrs.setText("0.00");
            }else{
                JFrame j=new JFrame();
                j.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(j, "Invalid Input", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
                
//                System.out.println("Number Format is InCorrect: "+ex.getMessage());
            }
        }
    }

    private void frmFmrPer() {
        try{
           fmr.setText(round((Float.parseFloat(fmrrs.getText())*100)/Float.parseFloat(grossAmt.getText()),3)+"");
        }catch(NumberFormatException ex){
        }
    }
    /**
     * Round to certain number of decimals
     * 
     * @param d
     * @param decimalPlace
     * @return
     */
    public static float round(float d, int decimalPlace) {
        BigDecimal bd = new BigDecimal(Float.toString(d));
        bd = bd.setScale(decimalPlace, BigDecimal.ROUND_HALF_UP);
        return bd.floatValue();
    }
    public static BigDecimal round(BigDecimal d, int decimalPlace) {
        d = d.setScale(decimalPlace, BigDecimal.ROUND_HALF_UP);
        return d;
    }

     public void setAllFieldData() {
        if(totalQty.getText().isEmpty()){
            totalQty.setText("0");
        }
        if(taxPer.getText().isEmpty()){
            taxPer.setText("0");
        }
        if(discPer.getText().isEmpty()){
            discPer.setText("0");
        }
        if(rate.getText().isEmpty()){
            rate.setText("0");
        }
        frmGrossAmount();
        frmTaxRs();
        frmDiscRs();
        frmNetAmount();
    }
    public void frmCtn(String s) {
        if(Float.parseFloat(s)!=0&&!totalQty.getText().equals("")){
            float f = Float.parseFloat(totalQty.getText())/Float.parseFloat(s);int i = (int)f;ctn.setText(i+"");
            System.out.println("i"+i);
        }
    }
    public void frmPcs(String s) {
        if(Float.parseFloat(s)!=0&&!totalQty.getText().equals("")){float f = Float.parseFloat(totalQty.getText())%Float.parseFloat(s);int i=(int)f;pcs.setText(i+"");}
    }
    public String getNoOfPcsInCtn() {
        String s="0";
        PAK_GENERAL_DB data= new PAK_GENERAL_DB();
        Connection conn=null;
        try{
            conn=data.connect_database();        
            s=data.getNoOfPcsInCtn(conn,seek.getText());
            data.close_database(conn);
        }catch(SQLException ex){System.out.println("ex : "+ex);}
        
        return s;
    }

    private void frmQty() {
        float f=(Float.parseFloat(ctn.getText())*Float.parseFloat(getNoOfPcsInCtn()))+Float.parseFloat(pcs.getText());
        totalQty.setText(f+"");        
    }
}
